// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyFlib;

#nullable disable

namespace MyFlib.Migrations
{
    [DbContext(typeof(LolDbContext))]
    [Migration("20230301171929_monNomDeMigration")]
    partial class monNomDeMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.2");

            modelBuilder.Entity("MyFlib.ChampionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("Class")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ImageId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ImageId");

                    b.ToTable("Champions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4422c524-b2cb-43ef-8263-990c3cea7cae"),
                            Bio = "",
                            Class = 1,
                            Icon = "",
                            ImageId = 1,
                            Name = "Akali"
                        },
                        new
                        {
                            Id = new Guid("a4f84d92-c20f-4f2d-b3f9-ca00ef556e72"),
                            Bio = "",
                            Class = 2,
                            Icon = "",
                            ImageId = 2,
                            Name = "Aatrox"
                        },
                        new
                        {
                            Id = new Guid("ae5fe535-f041-445e-b570-28b75bc78cb9"),
                            Bio = "",
                            Class = 3,
                            Icon = "",
                            ImageId = 1,
                            Name = "Ahri"
                        },
                        new
                        {
                            Id = new Guid("3708dcfd-02a1-491e-b4f7-e75bf274cf23"),
                            Bio = "",
                            Class = 4,
                            Icon = "",
                            ImageId = 1,
                            Name = "Akshan"
                        },
                        new
                        {
                            Id = new Guid("7f7746fa-b1cb-49da-9409-4b3e6910500e"),
                            Bio = "",
                            Class = 5,
                            Icon = "",
                            ImageId = 1,
                            Name = "Bard"
                        },
                        new
                        {
                            Id = new Guid("36ad2a82-d17b-47de-8a95-6e154a7df557"),
                            Bio = "",
                            Class = 6,
                            Icon = "",
                            ImageId = 1,
                            Name = "Alistar"
                        });
                });

            modelBuilder.Entity("MyFlib.LargeImageEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Base64")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("LargeImageEntity");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Base64 = "empty"
                        },
                        new
                        {
                            Id = 2,
                            Base64 = " "
                        });
                });

            modelBuilder.Entity("MyFlib.SkillEntity", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ChampionEntityId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Name");

                    b.HasIndex("ChampionEntityId");

                    b.ToTable("Skills");

                    b.HasData(
                        new
                        {
                            Name = "Boule de feu",
                            Description = "Fire!",
                            Type = 1
                        },
                        new
                        {
                            Name = "White Star",
                            Description = "Random damage",
                            Type = 3
                        });
                });

            modelBuilder.Entity("MyFlib.SkinEntity", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ChampionForeignKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ImageId")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Price")
                        .HasColumnType("REAL");

                    b.HasKey("Name");

                    b.HasIndex("ChampionForeignKey");

                    b.HasIndex("ImageId");

                    b.ToTable("Skins");

                    b.HasData(
                        new
                        {
                            Name = "Akali Infernale",
                            ChampionForeignKey = new Guid("4422c524-b2cb-43ef-8263-990c3cea7cae"),
                            Description = "Djinn qu'on invoque en dessous du monde, l'Infernale connue sous le nom d'Akali réduira en cendres les ennemis de son maître… mais le prix de son service est toujours exorbitant.",
                            Icon = "empty",
                            ImageId = 1,
                            Price = 520f
                        },
                        new
                        {
                            Name = "Akshan Cyberpop",
                            ChampionForeignKey = new Guid("3708dcfd-02a1-491e-b4f7-e75bf274cf23"),
                            Description = "Les bas-fonds d'Audio City ont un nouveau héros : le Rebelle fluo. Cette position, Akshan la doit à son courage, sa sagesse et sa capacité à s'infiltrer dans des bâtiments d'affaires hautement sécurisés, et ce, sans être repéré. Son charme ravageur l'a aussi beaucoup aidé.",
                            Icon = "empty",
                            ImageId = 2,
                            Price = 1350f
                        });
                });

            modelBuilder.Entity("MyFlib.ChampionEntity", b =>
                {
                    b.HasOne("MyFlib.LargeImageEntity", "Image")
                        .WithMany()
                        .HasForeignKey("ImageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Image");
                });

            modelBuilder.Entity("MyFlib.SkillEntity", b =>
                {
                    b.HasOne("MyFlib.ChampionEntity", null)
                        .WithMany("Skills")
                        .HasForeignKey("ChampionEntityId");
                });

            modelBuilder.Entity("MyFlib.SkinEntity", b =>
                {
                    b.HasOne("MyFlib.ChampionEntity", "Champion")
                        .WithMany("Skins")
                        .HasForeignKey("ChampionForeignKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyFlib.LargeImageEntity", "Image")
                        .WithMany()
                        .HasForeignKey("ImageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Champion");

                    b.Navigation("Image");
                });

            modelBuilder.Entity("MyFlib.ChampionEntity", b =>
                {
                    b.Navigation("Skills");

                    b.Navigation("Skins");
                });
#pragma warning restore 612, 618
        }
    }
}
