// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyFlib;

#nullable disable

namespace MyFlib.Migrations
{
    [DbContext(typeof(LolDbContext))]
    [Migration("20230204131532_MyMigration")]
    partial class MyMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.2");

            modelBuilder.Entity("MyFlib.ChampionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("Class")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Champions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Bio = "",
                            Class = 1,
                            Icon = "",
                            Image = "",
                            Name = "Akali"
                        },
                        new
                        {
                            Id = 2,
                            Bio = "",
                            Class = 2,
                            Icon = "",
                            Image = "",
                            Name = "Aatrox"
                        },
                        new
                        {
                            Id = 3,
                            Bio = "",
                            Class = 3,
                            Icon = "",
                            Image = "",
                            Name = "Ahri"
                        },
                        new
                        {
                            Id = 4,
                            Bio = "",
                            Class = 4,
                            Icon = "",
                            Image = "",
                            Name = "Akshan"
                        },
                        new
                        {
                            Id = 5,
                            Bio = "",
                            Class = 5,
                            Icon = "",
                            Image = "",
                            Name = "Bard"
                        },
                        new
                        {
                            Id = 6,
                            Bio = "",
                            Class = 6,
                            Icon = "",
                            Image = "",
                            Name = "Alistar"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
